version: '3.4'

services:
  shop-back.server:
    image: ${DOCKER_REGISTRY-}shopbackserver
    build:
      context: .
      dockerfile: shop-back.Server/Dockerfile
    ports:
      - 8008:8008
      - 4433:4433
    networks:
      - default
    environment:
      - ASPNETCORE_URLS=https://+:4433;http://+:8008
      - ASPNETCORE_Kestrel__Certificates__Default__Password=denis_555
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/sudohub.pfx
    volumes:
      - .secret:/https:ro
      - .db:/db:rw